/**
 * Bookstore API
 * Bookstore API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Book } from './book';


export interface Person { 
    id?: number;
    firstname?: string;
    lastname?: string;
    email?: string;
    books?: Array<Book>;
}

